In [34]:
# import requests
# import json
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns


import pokemon

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [33]:
generation_df(12,34)

,dex_id,name,type,type_2,hp,attack,defense,sp_atk,sp_def,speed
0,12,butterfree,bug,flying,60,45,50,90,80,70
1,13,weedle,bug,poison,40,35,30,20,20,50
2,14,kakuna,bug,poison,45,25,50,25,25,35
3,15,beedrill,bug,poison,65,90,40,45,80,75
4,16,pidgey,normal,flying,40,45,40,35,35,56
5,17,pidgeotto,normal,flying,63,60,55,50,50,71
6,18,pidgeot,normal,flying,83,80,75,70,70,101
7,19,rattata,normal,N/A,30,56,35,25,35,72
8,20,raticate,normal,N/A,55,81,60,50,70,97
9,21,spearow,normal,flying,40,60,30,31,31,70
10,22,fearow,normal,flying,65,90,65,61,61,100
11,23,ekans,poison,N/A,35,60,44,40,54,55
12,24,arbok,poison,N/A,60,95,69,65,79,80
13,25,pikachu,electric,N/A,35,55,40,50,50,90
14,26,raichu,electric,N/A,60,90,55,90,80,110
15,27,sandshrew,ground,N/A,50,75,85,20,30,40
16,28,sandslash,ground,N/A,75,100,110,45,55,65
17,29,nidoran-f,poison,N/A,55,47,52,40,40,41
18,30,nidorina,poison,N/A,70,62,67,55,55,56
19,31,nidoqueen,poison,ground,90,92,87,75,85,76
20,32,nidoran-m,poison,N/A,46,57,40,40,40,50
21,33,nidorino,poison,N/A,61,72,57,55,55,65